= mill-publishM2 - Publish artifacts to local Maven Repositories
:mill-publishM2-version: 0.1.3
:toc:
:toc-placement: preamble


Mill plugin to publish artifacts into a local Maven repository.

NOTE: *This mill plugin is now obsolete since Mill 0.6.2.
I migrated all of it's functionality into mill core.*

== Quickstart

Just mix-in the `PublishM2Module` into your project. `PublishM2Module` already extends mill's built-in `PublishModule`.

.File: `build.sc`
[source,scala,subs="verbatim,attributes"]
----
import mill._
import mill.scalalib._

import $ivy.`de.tototec::de.tobiasroeser.mill.publishM2:{mill-publishM2-version}`
import de.tobiasroeser.mill.publishM2._

object project extends PublishM2Module {
  // ...
}
----

.Shell: Publishing to default local Maven repository
----
> mill project.publishM2Local
[40/40] project.publishM2Local
Publishing to /home/user/.m2/repository
----

.Shell: Publishing to custom local Maven repository
----
> mill project.publishM2Local /tmp/m2repo
[40/40] project.publishM2Local
Publishing to /tmp/m2repo
----

== Version Compatibility Matrix

Mill is still in active development, and has no stable API yet.
Hence, not all mill-publishM2 versions work with every mill version.

The following table shows a matrix of compatible mill and mill-publishM2 versions.

.Version Compatibility Matrix
[options="header"]
|===
| mill-publishM2 | mill
| 0.1.3 | 0.6.0 - 0.6.2
| 0.1.2 | 0.5.7
| 0.1.0 | 0.3.6 - 0.5.3
| 0.0.2 | 0.3.2
| 0.0.1 | 0.2.8
|===


== License

Apache License, version 2.0

== Changelog

=== mill-publishM2 0.1.3 - 2020-03-11

* Version bump Mill API to 0.6.0

=== mill-publishM2 0.1.2 - 2020-01-22

* Version bump to mill 0.5.7

=== mill-publishM2 0.1.0 - 2019-02-26

* Version bump to mill 0.3.6
* `publishM2Local` now return `PathRef`s to published files
* Added test cases

=== mill-publishM2 0.0.2 - 2018-11-02

* Changed packaging and loading into mill by excluding mill dependencies

=== mill-publishM2 0.0.1 - 2018-10-19

* Initial release
